// <auto-generated />
using System;
using CarOrderingBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarOrderingBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221215135215_IntitialCreate")]
    partial class IntitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CarOrderingBackend.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaintId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RimsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TyresId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("PaintId");

                    b.HasIndex("RimsId");

                    b.HasIndex("TyresId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f8793de-1fd7-4c19-be36-36bb6ef03215"),
                            Name = "CustomCar1"
                        },
                        new
                        {
                            Id = new Guid("eccadda2-77ac-4f9e-a960-42a2ff232029"),
                            Name = "CustomCar2"
                        },
                        new
                        {
                            Id = new Guid("411eb5c4-b628-4c87-af77-a63769de382c"),
                            Name = "CustomCar3"
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.CarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db1bb43f-4dd4-4e3b-96fd-4322f89a24a4"),
                            ModelYear = 2020,
                            Name = "XC90"
                        },
                        new
                        {
                            Id = new Guid("171592d0-5034-4d9a-832a-5227b6650e7a"),
                            ModelYear = 2021,
                            Name = "S90"
                        },
                        new
                        {
                            Id = new Guid("a86aa4e4-881b-475c-96a3-db12902cfb2d"),
                            ModelYear = 2018,
                            Name = "V60"
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.Paint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaintType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Paints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a310079-ce3a-415b-9992-29b75a76e3ba"),
                            Color = "Midnight Blue",
                            PaintType = 0
                        },
                        new
                        {
                            Id = new Guid("7a2ef43a-0c57-446b-aecb-ad1b293332c3"),
                            Color = "Night Black",
                            PaintType = 1
                        },
                        new
                        {
                            Id = new Guid("00d3636a-df2b-43a3-b4f4-f98d904bc6de"),
                            Color = "Snow White",
                            PaintType = 2
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.Rims", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rims");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bbc9408-9c95-4e06-b3c9-078679fb06f9"),
                            Name = "Dragmaster",
                            Size = 18
                        },
                        new
                        {
                            Id = new Guid("e872b2b8-0172-4f66-8a79-c1b7396cd4ab"),
                            Name = "Occult",
                            Size = 19
                        },
                        new
                        {
                            Id = new Guid("883b2311-3168-455a-a54c-c97bc166fe80"),
                            Name = "Dream",
                            Size = 17
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.Tyres", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tyres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8da92000-acfc-42e2-bbac-e9852c24fbbc"),
                            Manufacturer = "Michelin",
                            SeasonType = 0
                        },
                        new
                        {
                            Id = new Guid("5511b992-7318-42d0-a388-4aecc3eb8d32"),
                            Manufacturer = "Continental",
                            SeasonType = 2
                        },
                        new
                        {
                            Id = new Guid("2e60fd51-81a2-40ae-88b7-1820a9c25ed4"),
                            Manufacturer = "Pirelli",
                            SeasonType = 1
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.Car", b =>
                {
                    b.HasOne("CarOrderingBackend.Models.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId");

                    b.HasOne("CarOrderingBackend.Models.Paint", "Paint")
                        .WithMany()
                        .HasForeignKey("PaintId");

                    b.HasOne("CarOrderingBackend.Models.Rims", "Rims")
                        .WithMany()
                        .HasForeignKey("RimsId");

                    b.HasOne("CarOrderingBackend.Models.Tyres", "Tyres")
                        .WithMany()
                        .HasForeignKey("TyresId");

                    b.Navigation("CarModel");

                    b.Navigation("Paint");

                    b.Navigation("Rims");

                    b.Navigation("Tyres");
                });
#pragma warning restore 612, 618
        }
    }
}
