// <auto-generated />
using System;
using CarOrderingBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarOrderingBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221207141038_IntitialCreate")]
    partial class IntitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CarOrderingBackend.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaintId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RimId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TyreId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfad21e4-c1d6-44ac-9117-a91689e22ddc"),
                            CarModelId = new Guid("6cf296b8-66bd-419a-8532-ecda364e42fa"),
                            PaintId = new Guid("544a8644-3572-4daf-a615-174843429997"),
                            RimId = new Guid("f5ab9bbd-5d3d-4de0-9c8a-179b44e281e7"),
                            TyreId = new Guid("067de25c-5842-4d57-92a5-e26ab856bbd9")
                        },
                        new
                        {
                            Id = new Guid("69b9217f-1dbd-4dc9-8a48-90ab90e9f4a1"),
                            CarModelId = new Guid("2fb81c08-2593-42c3-b3c1-cfc9ebf38fd7"),
                            PaintId = new Guid("567344be-1cb1-4dd2-8001-030339b4f705"),
                            RimId = new Guid("15a31af7-9d0c-4bee-a377-5b38fe5d9b38"),
                            TyreId = new Guid("22c54800-560c-4ee7-a8c3-6026ab684d65")
                        },
                        new
                        {
                            Id = new Guid("ea8f91d6-6d8a-463e-9dd4-7213dc70083b"),
                            CarModelId = new Guid("5d1d2b66-9d55-4074-8712-6caad55d569a"),
                            PaintId = new Guid("544a8644-3572-4daf-a615-174843429997"),
                            RimId = new Guid("15a31af7-9d0c-4bee-a377-5b38fe5d9b38"),
                            TyreId = new Guid("067de25c-5842-4d57-92a5-e26ab856bbd9")
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.CarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cf296b8-66bd-419a-8532-ecda364e42fa"),
                            ModelYear = 2020,
                            Name = "XC90"
                        },
                        new
                        {
                            Id = new Guid("2fb81c08-2593-42c3-b3c1-cfc9ebf38fd7"),
                            ModelYear = 2021,
                            Name = "S90"
                        },
                        new
                        {
                            Id = new Guid("5d1d2b66-9d55-4074-8712-6caad55d569a"),
                            ModelYear = 2018,
                            Name = "V60"
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.Paint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaintType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Paints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("544a8644-3572-4daf-a615-174843429997"),
                            Color = "Midnight Blue",
                            PaintType = 0
                        },
                        new
                        {
                            Id = new Guid("567344be-1cb1-4dd2-8001-030339b4f705"),
                            Color = "Space Black",
                            PaintType = 1
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.Rims", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rims");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5ab9bbd-5d3d-4de0-9c8a-179b44e281e7"),
                            Name = "Dragmaster",
                            Size = 18
                        },
                        new
                        {
                            Id = new Guid("15a31af7-9d0c-4bee-a377-5b38fe5d9b38"),
                            Name = "Occult",
                            Size = 19
                        });
                });

            modelBuilder.Entity("CarOrderingBackend.Models.Tyres", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tyres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("067de25c-5842-4d57-92a5-e26ab856bbd9"),
                            Manufacturer = "Michelin",
                            SeasonType = 0
                        },
                        new
                        {
                            Id = new Guid("22c54800-560c-4ee7-a8c3-6026ab684d65"),
                            Manufacturer = "Continental",
                            SeasonType = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
